In [1]:
import pandas as pd

In [2]:
folder = '/home/manikaran/M.tech/Minor project/data/CSR_NEW_FILES'

In [3]:
parties_in_nda = [
 'All India N.R. Congress',
 'Apna Dal',
 'Bharatiya Janta Party',
 'Janata Dal (United)',
 'Lok Jan Shakti Party',
 'Naga Peoples Front',
 "National People's Party",
 'Pattali Makkal Katchi',
 'Rashtriya Lok Samta Party',
 'Shiromani Akali Dal',
 'Shiv Sena',
 'Swabhimani Paksha',
 'Telugu Desam']

In [4]:
districtsDf = pd.read_csv('/home/manikaran/M.tech/Minor project/data/CSR_Districts_AspirantDistricts.csv')
districtsDf.head()

   Unnamed: 0                State              District  Aspirant_District
0           0  Andaman and Nicobar               Nicobar                  0
1           1  Andaman and Nicobar  North Middle Andaman                  0
2           2  Andaman and Nicobar         South Andaman                  0
3           3       Andhra Pradesh             Anantapur                  0
4           4       Andhra Pradesh              Chittoor                  0

In [5]:
RS_MPLAD_df = pd.read_csv('/home/manikaran/M.tech/Minor project/data/MPLADS/RajyaSabha2014MPLAD.csv')
RS_MPLAD_df.dropna(inplace=True)
RS_MPLAD_df.head()

,Unnamed: 0,Minister,state,MPLAD_District,CSR District,ministries
0,0,Arun Jaitley,Gujarat,Nadiad,Kheda,"[21,16,19]"
1,1,Piyush Goyal,Maharashtra,Mumbai City,Mumbai City,"[18,38,10]"
2,2,Nirmala Sitharaman,Andhra Pradesh,West Godavari,West Godavari,[43]
3,3,Prakash Javadekar,Madhya Pradesh,Chhindwara,Chhindwara,[48]
4,4,Venkaiah Naidu,Karnataka,Bengalore Urban,Bangalore Urban,"[35,45]"

In [6]:
#tempDf = districtsDf.merge(RS_MPLAD_df, how='left', left_on=['District', 'State'], right_on=['CSR District', 'state'])
#districtsDf = tempDf[['State', 'District', 'Aspirant_District', 'Minister', 'ministries']]
#districtsDf.columns = ['State', 'District', 'Aspirant_District', 'MPLAD_RajyaSabhaMinister', 'MPLAD_Ministries']
#districtsDf['MPLAD_Ministries'] = districtsDf['MPLAD_Ministries'].fillna('[]')
#districtsDf.head()

In [7]:
matrixDf = pd.read_csv('{}/20_SECTORS_MINISTRY_MATRIX.csv'.format(folder), delimiter='\t')
matrixDf.fillna('0', inplace=True)
matrixDf.rename(mapper={'Unnamed: 0': 'SectorCode'}, inplace=True, axis=1)
matrixDf.drop('Unnamed: 1', inplace=True, axis=1)
matrixDf.drop(0, inplace=True)
matrixDf['SectorCode'] = matrixDf['SectorCode'].astype(int)
#matrixDf['SectorCode'] = matrixDf['SectorCode'].apply(lambda x:  '{0:0>2}'.format(str(int(x))))
matrixDf.head()

   SectorCode  1  2  3  4  5  6  7  8  9 ... 43 44 45 46 47 48 49 50 51 52
1           1  0  0  0  0  0  0  0  1  1 ...  0  1  0  0  0  0  0  0  0  0
2           2  1  1  0  0  0  1  0  1  1 ...  0  0  0  1  0  0  0  0  0  0
3           3  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  1  0  0  0  0
4           4  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
5           5  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0

[5 rows x 53 columns]

In [8]:
ministersDf = pd.read_csv('{}/ministers2014-15Final.csv'.format(folder))
ministersDf['isMPMinister'] = [1]*ministersDf.shape[0]
ministersDf['LokSabhaConstituency'] = ministersDf['LokSabhaConstituency'].apply(str.upper)
ministersDf.head()

,Unnamed: 0,ministers,ministry,minCode,LokSabhaConstituency,isMPMinister
0,0,Col Rajyavardhan Singh Rathore (Retd.) AVSM,['Information and Broadcasting'],[19.0],JAIPUR RURAL,1
1,1,Dr. Harsh Vardhan,"['Science and Technology', 'Earth Sciences']","[6.0, 23.0]",CHANDNI CHOWK,1
2,2,Dr. Jitendra Singh,['Development of North Eastern Region (Indepen...,"[20.0, 39.0, 8.0]",UDHAMPUR,1
3,3,Dr. Mahesh Sharma,"['Tourism (Independent Charge)', 'Culture (Ind...","[14.0, 2.0, 36.0]",GAUTAM BUDHHA NAGAR,1
4,4,Dr. Sanjeev Kumar Balyan,['Agriculture'],[37.0],MUZAFFARNAGAR,1

In [9]:
#district to constituency mapping
'''data = []
for i in range(ministersDf.shape[0]):
    if not pd.isna(ministersDf.iloc[i]['CSR_District']):
        dis = eval(ministersDf.iloc[i]['CSR_District'])
        for d in dis:
            data.append([d, ministersDf.iloc[i]['State'], ministersDf.iloc[i]['Constituency']])
districtToMinConstDf = pd.DataFrame(data)
districtToMinConstDf.columns = ['district', 'state', 'constituency']
districtToMinConstDf.head()'''

"data = []\nfor i in range(ministersDf.shape[0]):\n    if not pd.isna(ministersDf.iloc[i]['CSR_District']):\n        dis = eval(ministersDf.iloc[i]['CSR_District'])\n        for d in dis:\n            data.append([d, ministersDf.iloc[i]['State'], ministersDf.iloc[i]['Constituency']])\ndistrictToMinConstDf = pd.DataFrame(data)\ndistrictToMinConstDf.columns = ['district', 'state', 'constituency']\ndistrictToMinConstDf.head()"

In [10]:
districtsToConstDf = pd.read_csv('{}/districtsWithConstDetails.csv'.format(folder))
districtsToConstDf['State'] = districtsToConstDf['State'].map(str.upper)
districtsToConstDf['District'] = districtsToConstDf['District'].map(str.upper)

#adding ministers info in district to loksabha constituency dataframe
tempDf = pd.DataFrame(ministersDf)
tempDf['LokSabhaConstituency'] = tempDf['LokSabhaConstituency'].map(lambda x: x.upper().strip())
districtsToConstDf = districtsToConstDf.merge(tempDf[['isMPMinister', 'ministry', 'minCode', 'LokSabhaConstituency']], how='left', on='LokSabhaConstituency')
districtsToConstDf['isMPMinister'] = districtsToConstDf['isMPMinister'].fillna(0)
districtsToConstDf.rename(mapper={'ministry':'LokSabha_Ministry', 'minCode':'LokSabha_MinCode'}, axis=1, inplace=True)
districtsToConstDf['LokSabha_MinCode'] = districtsToConstDf['LokSabha_MinCode'].fillna('[]')
districtsToConstDf['LokSabha_Ministry'] = districtsToConstDf['LokSabha_Ministry'].fillna('[]')
districtsToConstDf['Margin %'] = districtsToConstDf['Margin %'].map(lambda x: x.rstrip(' %') if not pd.isna(x) else x)
districtsToConstDf.head()

,Unnamed: 0,District,State,LokSabhaConstituency,Constituency,No,Type,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %,PartyShort,isMPMinister,LokSabha_Ministry,LokSabha_MinCode
0,0,NICOBAR,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,1.0,GEN,Bishnu Pada Ray,Bharatiya Janta Party,269360.0,190328.0,70.7 %,7812.0,4.1,BJP,0.0,[],[]
1,1,NORTH MIDDLE ANDAMAN,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,1.0,GEN,Bishnu Pada Ray,Bharatiya Janta Party,269360.0,190328.0,70.7 %,7812.0,4.1,BJP,0.0,[],[]
2,2,SOUTH ANDAMAN,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,ANDAMAN AND NICOBAR,1.0,GEN,Bishnu Pada Ray,Bharatiya Janta Party,269360.0,190328.0,70.7 %,7812.0,4.1,BJP,0.0,[],[]
3,3,ANANTAPUR,ANDHRA PRADESH,ANANTAPUR,ANANTAPUR,36.0,GEN,J.C. Divakar Reddi,Telugu Desam,1536912.0,1205054.0,78.4 %,61269.0,5.1,TDP,0.0,[],[]
4,4,ANANTAPUR,ANDHRA PRADESH,HINDUPUR,HINDUPUR,37.0,GEN,Kristappa Nimmala,Telugu Desam,1446503.0,1177257.0,81.4 %,97325.0,8.3,TDP,0.0,[],[]

In [11]:
stateDf = pd.read_csv('{}/stateGovernment2014New.csv'.format(folder))
stateDf['State'] = stateDf['State'].apply(lambda x: x.upper().strip())
stateDf.rename(mapper={'PartyShort':'PartyInState'}, axis=1, inplace=True)
stateDf.index = stateDf['State']
stateDf['PartyInState'] = stateDf['PartyInState'].map(eval)
partyInState = stateDf[['PartyInState', 'Party']].to_dict(orient='index')

In [12]:
partyInState

{'ANDHRA PRADESH': {'PartyInState': ['TDP'], 'Party': 'Telugu Desam Party'},
 'ARUNACHAL PRADESH': {'PartyInState': ['BJP'],
  'Party': 'Bharatiya Janata Party'},
 'ASSAM': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'BIHAR': {'PartyInState': ['BJP', 'JDU'], 'Party': 'Bharatiya Janata Party'},
 'CHHATTISGARH': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'DELHI': {'PartyInState': ['AAP'], 'Party': 'Aam Aadmi Party'},
 'GOA': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'GUJARAT': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'HARYANA': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'HIMACHAL PRADESH': {'PartyInState': ['INC'],
  'Party': 'Indian national Congress'},
 'JAMMU AND KASHMIR': {'PartyInState': [], 'Party': '---'},
 'JHARKHAND': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'KARNATAKA': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'KERALA': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'MADHYA PRADESH': {'PartyInState': ['BJP'],
  'Party': 'Bharatiya Janata Party'},
 'MAHARASHTRA': {'PartyInState': ['BJP', 'SS'],
  'Party': 'Bharatiya Janata Party'},
 'MANIPUR': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'MEGHALAYA': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'MIZORAM': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'NAGALAND': {'PartyInState': ['NPF'], 'Party': 'Nagaland Peoples Front'},
 'ODISHA': {'PartyInState': ['BJD'], 'Party': 'Biju Janata Dal'},
 'PUDUCHERRY': {'PartyInState': ['AINRC'], 'Party': 'All India N R Congress'},
 'PUNJAB': {'PartyInState': ['BJP', 'SAD'], 'Party': 'Bharatiya Janata Party'},
 'RAJASTHAN': {'PartyInState': ['BJP'], 'Party': 'Bharatiya Janata Party'},
 'SIKKIM': {'PartyInState': ['SDF'], 'Party': 'Sikkim Democratic Front'},
 'TAMIL NADU': {'PartyInState': ['AIADMK'],
  'Party': 'All India Anna Dravida Munnetra Kazhagam'},
 'TELANGANA': {'PartyInState': ['TRS'], 'Party': 'Telangana Rashtra Samithi'},
 'TRIPURA': {'PartyInState': ['CPIM'],
  'Party': 'Communist Party of India (Marxist) '},
 'UTTAR PRADESH': {'PartyInState': ['SP'], 'Party': 'Samajwadi Party'},
 'UTTARAKHAND': {'PartyInState': ['INC'], 'Party': 'Indian national Congress'},
 'WEST BENGAL': {'PartyInState': ['AITC'],
  'Party': 'All India Trinamool Congress'}}

In [13]:
# MPs Alignment with center
centerAlignment = []
stateAlignment = []
for i in range(districtsToConstDf.shape[0]):
    party = districtsToConstDf.iloc[i]['Party']
    partyShort = districtsToConstDf.iloc[i]['PartyShort']
    state = districtsToConstDf.iloc[i]['State']
    if party in parties_in_nda:
        centerAlignment.append(1)
    else:
        centerAlignment.append(0)
    if state not in partyInState:
        print(state)
        stateAlignment.append(0)
        continue
    if partyShort in partyInState[state]['PartyInState']:
        stateAlignment.append(1)
    else:
        stateAlignment.append(0)
districtsToConstDf['centerAlignment'] = centerAlignment
districtsToConstDf['stateAlignment'] = stateAlignment

ANDAMAN AND NICOBAR
ANDAMAN AND NICOBAR
ANDAMAN AND NICOBAR
CHANDIGARH
DADRA AND NAGAR HAVELI
DAMAN AND DIU
DAMAN AND DIU
LAKSHADWEEP

In [14]:
#putting all records in one file totalCSR<Fy>.csv
for fy in ['2014-15']: #,'2015-16', '2016-17']:
    data = []
    for i in range(districtsDf.shape[0]):
        state = districtsDf.iloc[i]['State']
        district = districtsDf.iloc[i]['District']
        is_backward = districtsDf.iloc[i]['Aspirant_District']
        constituency = (districtsToConstDf['District'] == district) & ((districtsToConstDf['District'] == district))
        tempDf = RS_MPLAD_df[(RS_MPLAD_df['state'] == state) & (district == RS_MPLAD_df['CSR District'])]
        if tempDf.shape[0] == 0:
            mplad_rs = 0
            rs_min_name = []
            mplad_ministers_ministry = []
        else:
            mplad_rs = 1
            rs_min_name = []
            mplad_ministers_ministry = []
            for j in range(tempDf.shape[0]):
                rs_min_name.append(tempDf.iloc[j]['Minister'])
                mplad_ministers_ministry += eval(tempDf.iloc[j]['ministries'])
        path = '{}/{}/{}/{}.csv'.format(folder, fy, state, district)
        tempDf = pd.read_csv(path)
        for c in range(tempDf.shape[0]):
            data.append([tempDf.iloc[c]['company'], state, district, is_backward, mplad_rs, rs_min_name, mplad_ministers_ministry,tempDf.iloc[c]['amount']])
        if tempDf.shape[0] == 0:
            data.append([None, state, district, is_backward, mplad_rs, rs_min_name, mplad_ministers_ministry, 0])
    print(len(data), 'records in', fy)
    df = pd.DataFrame(data)
    df.columns = ['company', 'state', 'district', 'is_backward', 'rs_min_mplad_district', 'rs_min_name', 'rs_min_ministry','amount']
    df['state'] = df['state'].map(lambda x: x.upper().strip())
    df['district'] = df['district'].map(lambda x: x.upper().strip())
    df.to_csv('{}/{}/{}.csv'.format(folder, fy, 'CSR_data'))
    dataDf = df.merge(districtsToConstDf, how='left', left_on=['district', 'state'], right_on=['District', 'State'])
    cols = ['company', 'state','district', 'Constituency', 'Type', 'Party', 'PartyShort', 'centerAlignment', 'stateAlignment', 'is_backward', 'Winning Candidate', 'LokSabha_Ministry', 'LokSabha_MinCode', 'isMPMinister', 'rs_min_mplad_district', 'rs_min_name', 'rs_min_ministry', 'Margin %' ,'amount']
    dataDf[cols].to_csv('{}/{}/{}.csv'.format(folder, fy, 'totalCSRAllConstAnalysis1'))
    print('Data items after merging', dataDf.shape)
    print(sum(pd.isna(dataDf['company'])), 'companies are NA, Amount: ', dataDf[pd.isna(dataDf['company'])]['amount'].sum())
    print(sum(pd.isna(dataDf['LokSabhaConstituency'])), 'Lok Sabha Constituencies are NA')

3687 records in 2014-15
Data items after merging (8571, 28)
402 companies are NA, Amount:  0
24 Lok Sabha Constituencies are NA

In [15]:
import numpy as np
def getMinistries(sector):
    if pd.isna(sector):
        return []
    tempDf = matrixDf[matrixDf['SectorCode'] == sector]
    #getting column number where values in the row == 1, 
    #since the ministry code starts from 1 and the first column header is SectorCode so
    #the indices return by where function is actually the ministry code
    return list(np.where(np.array(tempDf[:]=='1'))[1])

In [25]:
#adding CIN
for fy in ['2014-15']: #, '2015-16', '2016-17']:
    csrDf = pd.read_csv('{}/{}/{}.csv'.format(folder, fy, 'totalCSRAllConstAnalysis1'))
    compWithCINDf = pd.read_csv('{}/all_companies_2014_with_sector.csv'.format(folder))
    compWithCINDf = compWithCINDf[['company', 'CIN', 'buss_sector', 'sectorCode']]
    nic = []
    ministries = []
    year = []
    for i in range(compWithCINDf.shape[0]):
        ministries.append(getMinistries(compWithCINDf.iloc[i]['sectorCode']))
    compWithCINDf['ministriesInfluenced'] = ministries
    #compWithCINDf.to_csv('{}/{}/{}.csv'.format(folder, fy, 'companies'))
    csrDf['company'] = csrDf['company'].map(str.upper, na_action='ignore')
    tempDf = csrDf.merge(compWithCINDf, how='left', on='company')
    print(tempDf['CIN'].isna().sum(), 'None values', tempDf['company'].isna().sum())
    #tempDf.to_csv('{}/{}/{}.csv'.format(folder, fy, 'totalCSRWithComp{}'.format(fy)))
    ministryInfluenceComp = []
    for i in range(tempDf.shape[0]):
        intersection = 0
        minInfluenced = tempDf.iloc[i]['ministriesInfluenced']
        if pd.isna(tempDf.iloc[i]['CIN']):
            ministryInfluenceComp.append(0)
            continue
        if tempDf.iloc[i]['isMPMinister'] == 1:
            mins = eval(tempDf.iloc[i]['LokSabha_MinCode'])
            for ministry in minInfluenced:
                if ministry in mins:
                    intersection = 1
        if tempDf.iloc[i]['rs_min_mplad_district'] == 1:
            mins = eval(tempDf.iloc[i]['rs_min_ministry'])
            for ministry in minInfluenced:
                if ministry in mins:
                    intersection = 1
        ministryInfluenceComp.append(intersection)
    tempDf['ministry_comp_intersection'] = ministryInfluenceComp
    tempDf.to_csv('{}/{}/{}.csv'.format(folder, fy, 'totalCSRAllConstLinearReg'))

402 None values 402

In [34]:
tempDf.columns

Index(['Unnamed: 0', 'company', 'state', 'district', 'Constituency', 'Type',
       'Party', 'PartyShort', 'centerAlignment', 'stateAlignment',
       'is_backward', 'Winning Candidate', 'LokSabha_Ministry',
       'LokSabha_MinCode', 'isMPMinister', 'rs_min_mplad_district',
       'rs_min_name', 'rs_min_ministry', 'Margin %', 'amount', 'CIN',
       'buss_sector', 'sectorCode', 'ministriesInfluenced',
       'ministry_comp_intersection'],
      dtype='object')

In [32]:
(tempDf[tempDf['ministry_comp_intersection'] == 1]).reset_index(drop=True)[['company', 'CIN', 'Constituency', 'state', 'district', 'Party', 'Winning Candidate', 'LokSabha_Ministry', 'rs_min_name', 'rs_min_ministry', 'ministriesInfluenced' , 'buss_sector', 'amount']].to_csv('ministry_comp_intersection.csv')

In [40]:
(tempDf[(tempDf['stateAlignment'] == 1) & (tempDf['amount'] != '0')]).reset_index(drop=True)[['company', 'CIN', 'Constituency', 'state', 'district', 'Party', 'Winning Candidate', 'amount']].to_csv('stateAligned.csv')

In [17]:
def Or(series):
    ans = 0
    for s in series:
        ans = ans or s
    return ans

In [18]:
def Sum(series):
    total = 0
    for x in series:
        x = int(x.replace(',','').replace('.',''))
        total += x
    return total

In [19]:
fy = '2014-15'
totalCSRDf = pd.read_csv('{}/{}/totalCSRAllConstLinearReg.csv'.format(folder, fy))
reqdCols = ['Constituency', 'state', 'district', 'Type', 'Margin %', 'isMPMinister', 'centerAlignment', 'stateAlignment', 'rs_min_mplad_district', 'is_backward', 'ministry_comp_intersection', 'amount']
dataDf = totalCSRDf[reqdCols]
groupedDf = dataDf.groupby(['Constituency', 'state', 'Type', 'Margin %', 'isMPMinister', 'centerAlignment', 'stateAlignment'])

In [20]:
tempDf = groupedDf.agg({'rs_min_mplad_district':Or, 'is_backward':Or, 'ministry_comp_intersection':Or, 'amount':Sum}).reset_index()

In [21]:
tempDf.isna().any()

Constituency                  False
state                         False
Type                          False
Margin %                      False
isMPMinister                  False
centerAlignment               False
stateAlignment                False
rs_min_mplad_district         False
is_backward                   False
ministry_comp_intersection    False
amount                        False
dtype: bool

In [22]:
tempDf.head()

,Constituency,state,Type,Margin %,isMPMinister,centerAlignment,stateAlignment,rs_min_mplad_district,is_backward,ministry_comp_intersection,amount
0,ADILABAD,TELANGANA,ST,16.4,0.0,0,1,0,1,0,150000000
1,AGRA,UTTAR PRADESH,SC,28.1,1.0,1,0,0,0,0,1090000000
2,AHMEDABAD EAST,GUJARAT,GEN,33.1,0.0,1,1,0,0,0,90030000000
3,AHMEDABAD WEST,GUJARAT,SC,33.2,0.0,1,1,0,0,0,88400000000
4,AHMEDNAGAR,MAHARASHTRA,GEN,19.7,0.0,1,1,0,0,0,1370000000

In [23]:
tempDf["non_backward"] = tempDf["is_backward"].apply(lambda x: 0 if x == 1 else 1)

In [24]:
not_aligned = []
for i in range(tempDf.shape[0]):
    not_aligned.append(1-(tempDf.iloc[i]["stateAlignment"] or tempDf.iloc[i]["centerAlignment"]))
    print(tempDf.iloc[i]["stateAlignment"], tempDf.iloc[i]["centerAlignment"], 1-(tempDf.iloc[i]["stateAlignment"] or tempDf.iloc[i]["centerAlignment"]))
tempDf["not_aligned"] = not_aligned

1 0 0
0 1 0
1 1 0
1 1 0
1 1 0
1 1 0
0 1 0
1 1 0
1 0 0
0 0 1
0 1 0
1 0 0
0 1 0
0 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 0 1
1 1 0
1 1 0
0 0 1
0 1 0
1 1 0
1 1 0
1 1 0
1 1 0
0 0 1
0 1 0
0 1 0
1 0 0
0 0 1
1 0 0
1 0 0
0 0 1
1 1 0
0 0 1
1 1 0
0 1 0
1 0 0
0 0 1
1 1 0
1 1 0
1 0 0
1 0 0
1 0 0
0 1 0
0 1 0
0 0 1
0 1 0
1 1 0
1 0 0
0 1 0
1 0 0
1 1 0
0 1 0
0 1 0
0 1 0
1 0 0
0 1 0
1 0 0
0 0 1
1 0 0
0 1 0
1 1 0
1 1 0
0 1 0
0 0 1
0 0 1
1 0 0
1 0 0
1 0 0
1 1 0
0 1 0
1 0 0
1 1 0
0 0 1
1 0 0
1 0 0
1 1 0
0 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 1 0
1 0 0
1 1 0
0 1 0
1 0 0
0 0 1
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 0 0
1 1 0
1 0 0
0 1 0
0 1 0
0 1 0
1 1 0
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
0 1 0
1 1 0
1 1 0
0 0 1
1 0 0
0 1 0
0 1 0
0 1 0
1 1 0
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 1
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
1 1 0
1 1 0
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
0 1 0
1 1 0
0 1 0
0 1 0
1 1 0
1 1 0
0 1 0
1 1 0
0 1 0
0 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 1 0
0 1 0
1 0 0
0 0 1
1 1 0
1 0 0
0 1 0
1 0 0
1 1 0
0 1 0
1 0 0
0 0 1
0 0 1
0 1 0
1 1 0
1 0 0
1 0 0
0 1 0
0 1 0
0 1 0
1 1 0
0 0 1
0 1 0
0 0 1
0 1 0
0 1 0
1 0 0
1 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 1 0
0 1 0
1 1 0
1 0 0
0 1 0
0 1 0
0 1 0
1 1 0
1 1 0
0 1 0
1 1 0
0 1 0
1 0 0
0 0 1
0 1 0
1 1 0
1 1 0
1 1 0
0 0 1
0 1 0
0 1 0
0 1 0
0 1 0
0 0 1
0 1 0
0 1 0
0 1 0
1 1 0
1 1 0
0 0 1
0 0 1
1 0 0
1 1 0
1 1 0
1 0 0
0 0 1
0 0 1
1 1 0
1 0 0
1 1 0
1 0 0
1 0 0
0 1 0
1 1 0
1 1 0
1 0 0
0 0 1
0 1 0
1 1 0
1 1 0
1 1 0
1 0 0
0 1 0
1 1 0
1 1 0
0 1 0
0 0 1
1 1 0
0 1 0
1 0 0
1 1 0
1 1 0
0 1 0
1 0 0
1 1 0
1 1 0
0 1 0
1 1 0
1 1 0
0 0 1
0 1 0
0 1 0
1 1 0
1 0 0
1 0 0
1 0 0
1 1 0
1 0 0
1 0 0
0 1 0
1 1 0
1 0 0
0 1 0
0 0 1
0 1 0
1 0 0
0 1 0
1 1 0
0 0 1
1 0 0
1 1 0
1 0 0
0 0 1
0 0 1
0 1 0
1 0 0
1 0 0
1 1 0
0 1 0
1 1 0
0 0 1
1 1 0
1 1 0
1 1 0
0 1 0
1 1 0
0 0 1
1 1 0
0 0 1
1 0 0
0 0 1
1 0 0
1 0 0
0 0 1
0 1 0
1 0 0
1 1 0
1 1 0
0 0 1
1 0 0
1 0 0
1 0 0
0 0 1
1 1 0
0 1 0
0 1 0
0 1 0
0 0 1
0 1 0
1 1 0
1 1 0
0 1 0
0 0 1
0 1 0
0 1 0
0 0 1
0 0 1
1 1 0
1 0 0
1 0 0
1 1 0
0 1 0
1 1 0
1 0 0
1 1 0
1 0 0
0 0 1
0 0 1
0 0 1
0 1 0
0 1 0
1 1 0
1 1 0
0 0 1
0 1 0
0 1 0
1 0 0
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
1 0 0
0 1 0
0 1 0
0 1 0
1 0 0
0 1 0
0 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 0 1
0 1 0
1 1 0
0 1 0
1 0 0
1 1 0
1 0 0
0 0 1
1 1 0
0 1 0
1 1 0
0 1 0
1 1 0
0 0 1
1 0 0
0 0 1
1 1 0
0 0 1
1 1 0
0 1 0
1 1 0
1 1 0
1 1 0
0 0 1
0 1 0
1 0 0
1 0 0
0 1 0
1 1 0
0 1 0
0 1 0
0 0 1
1 1 0
1 0 0
0 0 1
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
1 0 0
0 0 1
1 1 0
1 0 0
1 0 0
0 1 0
0 1 0
1 0 0
1 1 0
0 0 1
1 1 0
0 1 0
1 1 0
1 0 0
1 1 0
1 0 0
1 1 0
0 0 1
1 0 0
1 1 0
0 0 1
1 1 0
1 1 0
1 1 0
0 0 1
1 1 0
1 1 0
0 0 1
1 1 0
1 1 0
1 0 0
0 1 0
1 1 0
1 0 0
1 1 0
1 1 0
1 1 0
1 1 0
1 1 0
0 1 0
0 0 1
1 1 0
1 1 0
0 1 0
1 0 0
0 1 0
0 1 0
1 0 0
0 1 0
1 1 0
0 0 1
0 1 0
1 1 0
1 1 0
0 0 1
1 1 0
0 1 0
1 1 0
0 1 0
1 1 0
1 0 0
0 1 0
0 1 0
1 1 0
1 1 0
0 1 0
1 1 0
1 1 0
1 0 0
1 0 0
1 1 0
0 0 1
0 1 0
0 1 0
1 0 0
1 1 0
1 1 0
1 1 0
0 1 0
1 1 0
1 0 0
1 1 0
0 0 1
1 0 0
0 1 0
0 1 0
0 0 1
1 1 0
1 1 0
1 1 0
1 0 0
0 1 0
1 0 0
0 1 0
1 1 0
1 0 0
1 0 0
1 0 0
1 0 0
0 0 1
1 1 0
1 0 0
1 0 0
0 0 1
1 0 0
1 0 0
1 0 0
1 1 0
1 0 0
1 0 0
1 0 0
0 1 0
1 1 0
0 1 0
0 1 0
1 1 0
1 1 0
1 0 0
0 1 0
0 1 0
1 0 0
1 1 0
0 1 0
1 1 0
1 1 0
0 1 0
1 0 0
1 1 0
1 1 0
1 0 0
1 0 0
0 1 0
1 1 0
1 1 0
1 0 0
0 1 0
1 1 0
1 0 0

In [14]:
(tempDf[tempDf['not_aligned'] == 1]).to_csv('not_aligned.csv')

In [21]:
(tempDf[tempDf['not_aligned'] == 1]['amount'].mean())/100000

60965.277777777774

In [25]:
(tempDf[(tempDf['stateAlignment'] == 1) & (tempDf['centerAlignment'] == 1)]['amount'].mean())/100000

108330.10204081633

In [28]:
tempDf[(tempDf['stateAlignment'] == 1) & (tempDf['centerAlignment'] == 0)]['amount'].mean()/100000

127182.70676691728

In [29]:
tempDf[(tempDf['stateAlignment'] == 0) & (tempDf['centerAlignment'] == 1)]['amount'].mean()/100000

50290.78014184397

In [30]:
tempDf[(tempDf['stateAlignment'] == 1) & (tempDf['centerAlignment'] == 1)].shape

(196, 13)

In [32]:
tempDf[(tempDf['stateAlignment'] == 0) & (tempDf['centerAlignment'] == 1)].shape

(141, 13)

In [33]:
tempDf[(tempDf['stateAlignment'] == 1) & (tempDf['centerAlignment'] == 0)].shape

(133, 13)

In [34]:
tempDf[tempDf['not_aligned'] == 1].shape

(72, 13)

In [25]:
tempDf.to_csv('{}/{}/dataForLinearRegressionAnalysis.csv'.format(folder, '2014-15'))

In [9]:
#added ministry codes to the linearRegression analysis final data
def concat(series):
    res = []
    for x in series:
        res += eval(x)
    return list(set(res))
fy='2014-15'
totalCSRDf = pd.read_csv('{}/{}/totalCSRAllConstLinearReg.csv'.format(folder, fy))
reqdCols2 = ['Constituency', 'state', 'district', 'Type', 'Margin %', 'isMPMinister', 'centerAlignment', 'stateAlignment', 'rs_min_mplad_district', 'is_backward', 'ministry_comp_intersection', 'LokSabha_MinCode', 'rs_min_ministry', 'amount']
dataDf2 = totalCSRDf[reqdCols2]
groupedDf2 = dataDf2.groupby(['Constituency', 'state', 'Type', 'Margin %', 'isMPMinister', 'centerAlignment', 'stateAlignment'])
tempDf2 = groupedDf2.agg({'rs_min_mplad_district':Or, 'is_backward':Or, 'ministry_comp_intersection':Or, 'amount':Sum, 'LokSabha_MinCode':concat, 'rs_min_ministry':concat}).reset_index()
tempDf2["non_backward"] = tempDf2["is_backward"].apply(lambda x: 0 if x == 1 else 1)
not_aligned = []
for i in range(tempDf2.shape[0]):
    not_aligned.append(1-(tempDf2.iloc[i]["stateAlignment"] or tempDf2.iloc[i]["centerAlignment"]))
tempDf2["not_aligned"] = not_aligned
tempDf2.to_csv('{}/{}/dataForLinearRegressionAnalysis2.csv'.format(folder, '2014-15'))