In [30]:
import pandas as pd

In [31]:
constToDistrictDf = pd.read_csv('ConstituencyToDistrictMapping.csv')

In [32]:
constToDistrictDf['State'] = constToDistrictDf['State'].apply(lambda x: eval(x)[0])

In [33]:
cabinetMinisterDf = pd.read_csv('./UnionMinisters/CabinetMinisterNames.csv')
independentMinisterDf = pd.read_csv('./UnionMinisters/IndependentChargeMinisterNames.csv')
minOfStatesDf = pd.read_csv('./UnionMinisters/MinistersOfStateNames.csv')

In [34]:
ministersDf = pd.concat((cabinetMinisterDf, independentMinisterDf, minOfStatesDf), axis=0)

In [35]:
ministersDf = ministersDf.reset_index(drop=True)
ministersDf.to_csv('./UnionMinisters/allMinistersName.csv')

In [36]:
constToDistrictDf['DistrictAliasName']=constToDistrictDf['DistrictAliasName'].map(eval)

In [37]:
ministersDf['Constituency']=ministersDf['Constituency'].map(str.upper, na_action='ignore')

In [38]:
mergedDf = ministersDf.merge(constToDistrictDf, how='left', left_on=['State','Constituency'], right_on=['State','LokSabhaConstituency'])

In [39]:
mergedDf[pd.isna(mergedDf['LokSabhaConstituency'])]

,Unnamed: 0_x,Minister,Constituency,Rajya Sabha,State,Unnamed: 0_y,LokSabhaConstituency,District,DistrictAliasName
3,3,Arun Jaitley,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,NaN
4,4,Piyush Goyal,NaN,1.0,Maharashtra,NaN,NaN,NaN,NaN
5,5,Manohar Parrikar,NaN,NaN,Goa,NaN,NaN,NaN,NaN
6,6,Nirmala Sitharaman,NaN,1.0,Karnataka,NaN,NaN,NaN,NaN
7,7,Prakash Javadekar,NaN,1.0,Maharashtra,NaN,NaN,NaN,NaN
8,8,Venkaiah Naidu,NaN,1.0,Rajasthan,NaN,NaN,NaN,NaN
9,9,Smriti Irani,NaN,1.0,Gujarat,NaN,NaN,NaN,NaN
12,12,Suresh Prabhu,NaN,1.0,Andhra Pradesh,NaN,NaN,NaN,NaN
15,15,Ravi Shankar Prasad,NaN,1.0,Bihar,NaN,NaN,NaN,NaN
20,20,Najma A. Heptulla,NaN,1.0,Madhya Pradesh,NaN,NaN,NaN,NaN
21,21,Mukhtar Abbas Naqvi,NaN,1.0,Jharkhand,NaN,NaN,NaN,NaN
33,33,Thawar Chand Gehlot,NaN,1.0,Madhya Pradesh,NaN,NaN,NaN,NaN
35,35,Jagat Prakash Nadda,NaN,1.0,Himachal Pradesh,NaN,NaN,NaN,NaN
38,38,Dharmendra Pradhan,NaN,1.0,Bihar,NaN,NaN,NaN,NaN
48,9,Hardeep Singh Puri,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,NaN
49,10,Alphons Kannanthanam,NaN,1.0,Rajasthan,NaN,NaN,NaN,NaN
50,0,Vijay Goel,NaN,1.0,Rajasthan,NaN,NaN,NaN,NaN
54,4,Ramdas Athawale,NaN,1.0,Maharashtra,NaN,NaN,NaN,NaN
61,11,Parshottam Rupala,NaN,1.0,Gujarat,NaN,NaN,NaN,NaN
65,15,Shiv Pratap Shukla,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,NaN
72,22,M. J. Akbar,NaN,1.0,Jharkhand,NaN,NaN,NaN,NaN

CSRDistrictsDf = pd.read_csv('/home/manikaran/M.tech/Minor project/data/districts_updated.csv')
districts=[]
for i in range(CSRDistrictsDf.shape[0]):
    state = CSRDistrictsDf.iloc[i][0]
    j = 1
    while j < CSRDistrictsDf.shape[1] and not pd.isna(CSRDistrictsDf.iloc[i][j]):
        districts.append([state, CSRDistrictsDf.iloc[i][j]])
        j += 1
(pd.DataFrame(districts, columns=['State', 'District'])).to_csv('/home/manikaran/M.tech/Minor project/data/CSR_Districts.csv')

In [40]:
CSRDistrictsDf = pd.read_csv('/home/manikaran/M.tech/Minor project/data/CSR_Districts.csv')

In [41]:
mergedDf = mergedDf.drop(['Unnamed: 0_x', 'Unnamed: 0_y'], axis=1)

In [42]:
CSR_Districts = []
for i in range(mergedDf.shape[0]):
    if pd.isna(mergedDf.iloc[i]['District']):
        CSR_Districts.append(None)
        continue
    state = mergedDf.iloc[i]['State']
    aliases = mergedDf.iloc[i]['DistrictAliasName']
    tempDf = CSRDistrictsDf[CSRDistrictsDf['State']==state]
    districts = []
    for j in range(len(aliases)):
        alias = aliases[j]
        for k in range(tempDf.shape[0]):
            if tempDf.iloc[k]['District'].strip() in alias:
                districts.append(tempDf.iloc[k]['District'])
                break
        else:
            if 'Bardhaman' in alias:
                districts.extend(['Purba Bardhaman', 'Paschim Bardhaman']) #since bardhaman is bifurcated and Bardhaman also exists in database
            else:    
                districts.append(None)
    CSR_Districts.append(districts)

In [43]:
mergedDf['CSR_District'] = CSR_Districts

In [44]:
mergedDf[pd.isna(mergedDf['CSR_District'])]

,Minister,Constituency,Rajya Sabha,State,LokSabhaConstituency,District,DistrictAliasName,CSR_District
3,Arun Jaitley,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,None
4,Piyush Goyal,NaN,1.0,Maharashtra,NaN,NaN,NaN,None
5,Manohar Parrikar,NaN,NaN,Goa,NaN,NaN,NaN,None
6,Nirmala Sitharaman,NaN,1.0,Karnataka,NaN,NaN,NaN,None
7,Prakash Javadekar,NaN,1.0,Maharashtra,NaN,NaN,NaN,None
8,Venkaiah Naidu,NaN,1.0,Rajasthan,NaN,NaN,NaN,None
9,Smriti Irani,NaN,1.0,Gujarat,NaN,NaN,NaN,None
12,Suresh Prabhu,NaN,1.0,Andhra Pradesh,NaN,NaN,NaN,None
15,Ravi Shankar Prasad,NaN,1.0,Bihar,NaN,NaN,NaN,None
20,Najma A. Heptulla,NaN,1.0,Madhya Pradesh,NaN,NaN,NaN,None
21,Mukhtar Abbas Naqvi,NaN,1.0,Jharkhand,NaN,NaN,NaN,None
33,Thawar Chand Gehlot,NaN,1.0,Madhya Pradesh,NaN,NaN,NaN,None
35,Jagat Prakash Nadda,NaN,1.0,Himachal Pradesh,NaN,NaN,NaN,None
38,Dharmendra Pradhan,NaN,1.0,Bihar,NaN,NaN,NaN,None
48,Hardeep Singh Puri,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,None
49,Alphons Kannanthanam,NaN,1.0,Rajasthan,NaN,NaN,NaN,None
50,Vijay Goel,NaN,1.0,Rajasthan,NaN,NaN,NaN,None
54,Ramdas Athawale,NaN,1.0,Maharashtra,NaN,NaN,NaN,None
61,Parshottam Rupala,NaN,1.0,Gujarat,NaN,NaN,NaN,None
65,Shiv Pratap Shukla,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,None
72,M. J. Akbar,NaN,1.0,Jharkhand,NaN,NaN,NaN,None

In [45]:
CSR_file = '/home/manikaran/M.tech/Minor project/data/CSR_NEW_FILES/{}/{}/Z_total.csv'

In [46]:
years = ['2014-15', '2015-16', '2016-17']
for fy in years:    
    amount = []
    for i in range(mergedDf.shape[0]):
        state = mergedDf.iloc[i]['State']
        districts = mergedDf.iloc[i]['CSR_District']
        if districts == None:
            amount.append(None)
            continue
        s = 0
        for d in districts:
            try:
                tempDf = pd.read_csv(CSR_file.format(fy,state))
                tempDf.columns = ['district', 'amount']
                #print(state,districts,tempDf[tempDf['district'] == d]['amount'])
                if pd.isna((tempDf[tempDf['district'] == d]['amount']).iloc[0]):
                    continue
                s += (tempDf[tempDf['district'] == d]['amount'].iloc[0])
            except Exception as e:
                print(e)
                print(d, tempDf)
        amount.append(s)
    mergedDf['CSR_Amount_' + fy] = amount

In [47]:
mergedDf.head()

,Minister,Constituency,Rajya Sabha,State,LokSabhaConstituency,District,DistrictAliasName,CSR_District,CSR_Amount_2014-15,CSR_Amount_2015-16,CSR_Amount_2016-17
0,Narendra Modi,VARANASI,NaN,Uttar Pradesh,VARANASI,['Varanasi'],[[Varanasi]],[Varanasi],43500000.0,64700000.0,211400000.0
1,Rajnath Singh,LUCKNOW,NaN,Uttar Pradesh,LUCKNOW,['Lucknow'],[[Lucknow]],[Lucknow],34800000.0,81900000.0,105200000.0
2,Sushma Swaraj,VIDISHA,NaN,Madhya Pradesh,VIDISHA,"['Vidisha', 'Raisen', 'Sehore', 'Dewas']","[[Vidisha], [Raisen], [Sehore], [Dewas]]","[Vidisha, Raisen, Sehore, Dewas]",85800000.0,58100000.0,32700000.0
3,Arun Jaitley,NaN,1.0,Uttar Pradesh,NaN,NaN,NaN,None,NaN,NaN,NaN
4,Piyush Goyal,NaN,1.0,Maharashtra,NaN,NaN,NaN,None,NaN,NaN,NaN

In [48]:
cols = ['Minister', 'Constituency', 'Rajya Sabha', 'State', 'District', 'CSR_District', 'CSR_Amount_2014-15', 'CSR_Amount_2015-16', 'CSR_Amount_2016-17' ]
mergedDf.to_csv('./UnionMinisters/ministers_district.csv', columns=cols)